services:
  mongodb:
    image: mongo:latest
    container_name: hybrid-search-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=search_service
    networks:
      - search-network

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: hybrid-search-opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "OPENSEARCH_PATH_CONF=/usr/share/opensearch/config"
    volumes:
      - ./opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 60s
      timeout: 60s
      retries: 5
      start_period: 180s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - search-network

networks:
  search-network:
    driver: bridge

volumes:
  mongodb_data:
  opensearch_data: